"""Fix created_ad in Tasks

Revision ID: dfb5bdb2b102
Revises: a365fd602811
Create Date: 2023-11-05 18:24:58.310630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb5bdb2b102'
down_revision: Union[str, None] = 'a365fd602811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
