"""Add hex column in workspace

Revision ID: 4f4d40ed94f8
Revises: 5836458f1107
Create Date: 2023-11-23 13:22:21.340026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4d40ed94f8'
down_revision: Union[str, None] = '5836458f1107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panels', 'name',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('workspaces', sa.Column('hex', sa.String(length=40), nullable=True))
    op.alter_column('workspaces', 'name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.drop_column('workspaces', 'hex')
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    op.alter_column('panels', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
