"""Delete panels order in Workspace and add task and panel positions

Revision ID: 8e40f0e1b0d8
Revises: 3291971a2cab
Create Date: 2023-12-08 19:23:34.882986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e40f0e1b0d8'
down_revision: Union[str, None] = '3291971a2cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panels', sa.Column('panel_position', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('task_position', sa.Integer(), nullable=True))
    op.drop_column('workspaces', 'panels_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('panels_order', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'task_position')
    op.drop_column('panels', 'panel_position')
    # ### end Alembic commands ###
