"""Add panels order column in workspace

Revision ID: 3291971a2cab
Revises: dac03099d235
Create Date: 2023-12-03 19:54:27.532940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3291971a2cab'
down_revision: Union[str, None] = 'dac03099d235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('panels_order', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'panels_order')
    # ### end Alembic commands ###
