"""Change names to parent_id

Revision ID: ba9056cd8cdc
Revises: f9e8644bd92e
Create Date: 2023-11-10 18:06:21.970715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9056cd8cdc'
down_revision: Union[str, None] = 'f9e8644bd92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panels', column_name='workspace_id', new_column_name='parent_id')
    op.alter_column('tasks', column_name='panel_id', new_column_name='parent_id')
    op.alter_column('workspaces', column_name='user_id', new_column_name='parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panels', column_name='parent_id', new_column_name='workspace_id')
    op.alter_column('tasks', column_name='parent_id', new_column_name='panel_id')
    op.alter_column('workspaces', column_name='parent_id', new_column_name='user_id')
    # ### end Alembic commands ###
