"""Change workspace model: add M2M relationship

Revision ID: 5836458f1107
Revises: 3ee60a236c43
Create Date: 2023-11-21 16:20:01.259193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5836458f1107'
down_revision: Union[str, None] = '3ee60a236c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], )
    )
    op.alter_column('workspaces', 'user_id', new_column_name='creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'creator_id', new_column_name='user_id')
    op.drop_table('workspace_members')
    # ### end Alembic commands ###
