"""Minor changes in Tasks

Revision ID: e6421ba61582
Revises: dfb5bdb2b102
Create Date: 2023-11-06 01:15:29.381019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6421ba61582'
down_revision: Union[str, None] = 'dfb5bdb2b102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
