"""Cascade delete workspace m2m

Revision ID: dac03099d235
Revises: bc225d5a1051
Create Date: 2023-12-01 13:14:08.613575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac03099d235'
down_revision: Union[str, None] = 'bc225d5a1051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workspace_members_workspace_id_fkey', 'workspace_members', type_='foreignkey')
    op.drop_constraint('workspace_members_member_id_fkey', 'workspace_members', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_members', 'user', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workspace_members', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.create_foreign_key('workspace_members_member_id_fkey', 'workspace_members', 'user', ['member_id'], ['id'])
    op.create_foreign_key('workspace_members_workspace_id_fkey', 'workspace_members', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###
