"""Delete is_completed from tasks

Revision ID: bc225d5a1051
Revises: 4f4d40ed94f8
Create Date: 2023-11-24 13:10:01.788151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc225d5a1051'
down_revision: Union[str, None] = '4f4d40ed94f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
