"""Change TODO model

Revision ID: 0e5300ed4e00
Revises: 646c9fac0502
Create Date: 2023-10-29 20:24:25.397106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5300ed4e00'
down_revision: Union[str, None] = '646c9fac0502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('todos', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('todos', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'is_completed')
    # ### end Alembic commands ###
